- name: nginx nstallation
  hosts: web
  become: yes
  tasks:  
  - name: nginx
    ansible.builtin.package:
      name: nginx
      state: installed
  - name: nginx service start
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes