- name: vars from file
  hosts: web
  vars_files:
  - vars.yaml
  tasks:
  - name: the varibles from the var file
    ansible.builtin.debug:
      msg: " i am learnign {{course}} duration is {{duration}} and trainer is {{trainer}}"
