- name: this isfor testing condition 
  hosts: web
  vars_prompt:
  - name: my_number
    prompt: please enter the number
  tasks:
  - name: check the condition wheteher number is less than 10
    ansible.builtin.debug:
      msg: " the number {{my_number}} is less than 10 "
    when: my_number | int < 10
