- name: Id checking
  hosts: web
  become: yes
  tasks:
  - name: id existence check
    ansible.builtin.command: id expense
    register: userid
    ignore_errors: true
  - name: print user details
    debug:
      msg: {{userid}}
  - name: user id creation
    ansible.builtin.command: useradd expense
    when: userid.rc !=0