- name: Id checking
  hosts: web
  tasks:
  - name: id existence check
    ansible.builtin.command: id expense
    register: userid
    ignore_errors: true
  - name: user id creation
    ansible.builtin.command: useradd expense
    when: userid.rc !=0