- name: loops with lists and disctionary
  hosts: web
  tasks:
  - name: the loops iteration
    debug:
      msg: "{{item.name}} ---- {{item.group}}"
    loop: 
      - {name: "name1", group: "root1" }
      - {name: "name2", group: "root2" }