- name: This EC2 instance creation
  hosts: localhost  # Fixed 'local' to 'localhost'
  connection: local
  vars:
    zone: "sankardevops.shop"
    subnet_id: "subnet-0bb4042a52cfcf8f3"
    sg_id: "sg-05b0b0c9126c60beb"
    ami_id: "ami-09c813fb71547fc4f"
    instances:
      - mysql
      - backend
      - frontend
  tasks:
    - name: Install boto3 and botocore
      ansible.builtin.pip:
        name:
          - boto3
          - botocore
        executable: pip3.9

    - name: Create EC2 instances
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        vpc_subnet_id: "{{ subnet_id }}"
        instance_type: "t3.micro"
        security_group: "{{ sg_id }}"
        image_id: "{{ ami_id }}"
      loop: "{{ instances }}"
      register: ec2_instances  # Fixed typo
