- name: This ec2 instance creation
  hosts: local
  become: yes
  vars:
    zone: "sankardevops.shop"
    subnet_id: "subnet-0bb4042a52cfcf8f3"
    image_id: "ami-09c813fb71547fc4f"
    instances:
      - mysql
      - backend
      - frontend
  tasks:
  - name: installation boto 3 and botocore 
    ansible.builtin.pip:
      name:
       - boto3
       - botocore
      executable: pip3.9
  - name: start an instance with a public IP address
    amazon.aws.ec2_instance:
      name: {{items}}
      vpc_subnet_id: {{subnet_id}}
      instance_type: "t3.micro"
      security_group: "allow-ssh"
      image_id: {{image_id}}
    loop: {{instances}}
    register: ec2_instance

  - name: creating the route 53 for mysql and backend
    amazon.aws.route53:
      state: present
      zone: "{{zone}}"
      record: "{{item.item}}.{{zone}}"
      type: A
      ttl: 1
      value: "{{item.instances[0].private_ip_address}}"
      wait: true
      overwrite: true
    loop: "{{ec2_instance.results}}"
    when: "{{item.item}}" != "frontend"

    - name: creating the route 53 for frontend
    amazon.aws.route53:
      state: present
      zone: "{{zone}}"
      record: "{{item.item}}.{{zone}}"
      type: A
      ttl: 1
      value: "{{item.instances[0].private_ip_address}}"
      wait: true
      overwrite: true
    loop: "{{ec2_instance.results}}"
    when: "{{item.item}}" == "frontend"
    

